services:
  # Serviços Hyperledger Besu
  bootnode:
    container_name: master
    image: hyperledger/besu:latest
    volumes:
      - ./besu:/config
    ports:
      - 8546:8546
      - 8545:8545
    command: >
      --config-file=/config/besu.toml --node-private-key-file=/config/key
    networks:
      besu-network:
        ipv4_address: 10.10.0.11
    expose:
      - 8548
      - 30303

  besu2:
    depends_on:
      - bootnode
    image: hyperledger/besu:latest
    volumes:
      - ./besu:/config
    command: >
      --bootnodes="enode://ba5734d8f7091719471e7f7ed6b9df170dc70cc661ca05e688601ad984f068b0d67351e5f06073092499336ab0839ef8a521afd334e53807205fa2f08eec74f4@10.10.0.11:30303" --config-file=/config/besu.toml
    networks:
      besu-network:
        ipv4_address: 10.10.0.12
    expose:
      - 8548
      - 30303

  besu3:
    depends_on:
      - bootnode
    image: hyperledger/besu:latest
    volumes:
      - ./besu:/config
    command: >
      --bootnodes="enode://ba5734d8f7091719471e7f7ed6b9df170dc70cc661ca05e688601ad984f068b0d67351e5f06073092499336ab0839ef8a521afd334e53807205fa2f08eec74f4@10.10.0.11:30303" --config-file=/config/besu.toml
    networks:
      besu-network:
        ipv4_address: 10.10.0.13
    expose:
      - 8548
      - 30303

  besu4:
    depends_on:
      - bootnode
    image: hyperledger/besu:latest
    volumes:
      - ./besu:/config
    command: >
      --bootnodes="enode://ba5734d8f7091719471e7f7ed6b9df170dc70cc661ca05e688601ad984f068b0d67351e5f06073092499336ab0839ef8a521afd334e53807205fa2f08eec74f4@10.10.0.11:30303" --config-file=/config/besu.toml
    networks:
      besu-network:
        ipv4_address: 10.10.0.14
    expose:
      - 8548
      - 30303

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - bootnode
    networks:
      - besu-network

  influxdb:
    image: influxdb:1.8
    networks:
      - besu-network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_DATA_MAX_CONCURRENT_WRITES=64
      - INFLUXDB_DATA_MAX_BODY_SIZE=100MB
      - INFLUXDB_HTTP_MAX_CONNECTIONS=1024
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    depends_on:
      - influxdb
    image: grafana/grafana:latest
    networks:
      - besu-network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  besu-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/24"
          gateway: "10.10.0.1"

volumes:
  influxdb_data:
