# Usar a imagem base do Nginx
FROM nginx:latest

# Copiar o conteúdo do diretório atual para o diretório de trabalho do container
COPY . /usr/share/nginx/html

# Expor a porta 80 para acesso HTTP
EXPOSE 80