services:
  besu:
    image: hyperledger/besu:latest
    volumes:
      - ./besu:/config
    ports:
      - 8545:8545
      - 8548:8548
    command: --config-file=/config/besu.toml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - besu
