services:
  besu:
    image: hyperledger/besu:latest
    volumes:
      - ./:/config
      - ./:/blockchain
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 8548:8548
    command: --config-file=/config/besu.toml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - besu

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
