services:
  besu:
    image: hyperledger/besu:latest
    volumes:
      - ./:/config
      - ./blockchain:/opt/besu/blockchain
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 8548:8548
    command: --config-file=/config/besu.toml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - besu

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alert-manager.yml:/prometheus/alert-manager.yml
    command:
      - "--config.file=/prometheus/alert-manager.yml"
    ports:
      - "9093:9093"
    depends_on:
      - prometheus

  # discord-alertmanager:
  #   image: 
