groups:
  - name: txmined_once
    rules:
      - alert: NewTransactionMined
        expr: rate(besu_blockchain_chain_head_transaction_count_counter_total[5s]) > 0
        for: 0s
        labels:
          team: newtx
        annotations:
          summary: "New transaction mined on the blockchain"
          description: "A new transaction was mined on the blockchain"
  - name: besu_availability
    rules:
      - alert: BesuDown
        expr: up{job="besu_node"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Besu node is down"
          description: "The Besu node {{ $labels.instance }} is down for more than 1 minute."
