groups:
  - name: besu_miner
    rules:
      - alert: BesuMiningStopped
        expr: rate(besu_blockchain_chain_head_timestamp[1m]) <= 1
        for: 2s
        labels:
          severity: critical
        annotations:
          summary: "Besu has stopped mining"
          description: "The Besu node has not produced any new blocks in the last 10 seconds."

  - name: besu_availability
    rules:
      - alert: BesuDown
        expr: up{job="besu_node"} == 0
        for: 2s
        labels:
          severity: critical
        annotations:
          summary: "Besu node is down"
          description: "The Besu node {{ $labels.instance }} is down for more than 10 seconds."
