global:
  scrape_interval: 1s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: "besu_node"
    scrape_interval: 1s
    static_configs:
      - targets: ["besu:8548"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
