global:
route:
  receiver: Discord
  group_by: ["alertname"]
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 2s

  routes:
    - receiver: Discord
      match:
        team: "txmined"

receivers:
  - name: Discord
    discord_configs:
      - webhook_url: "https://discord.com/api/webhooks/1283129693154971788/oVn6BKAj88rPGGEK034csoO5ynxFZ7egIr9dmBIPXMvCeD8Nj61OSVaISFEvOJT3cDNA"
        message: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
