{
 "title": "New dashboard",
 "time": { "from": "2024-07-23T21:15:58.357Z", "to": "2024-07-24T09:15:58.357Z" },
 "panels": [
  {
   "title": "Current Blocks per Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ethereum_best_known_block_number{instance=\"10.10.0.11:8548\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ethereum_best_known_block_number{instance=\"10.10.0.12:8548\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ethereum_best_known_block_number{instance=\"10.10.0.13:8548\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ethereum_best_known_block_number{instance=\"10.10.0.14:8548\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Counter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "besu_blockchain_chain_head_transaction_count_counter_total{instance=\"10.10.0.11:8548\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ethereum_peer_count{instance=\"10.10.0.11:8548\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}