services:
  nginx_v1:
    image: meu-nginx:1.0
    ports:
      - "8080:80"

  nginx_v2:
    image: meu-nginx:2.0
    ports:
      - "8081:80"

  nginx_v3:
    image: meu-nginx:3.0
    ports:
      - "8082:80"