networks:
  my_net:

volumes:
  influxdb_data:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - my_net

  influxdb:
    image: influxdb:1.8
    networks:
      - my_net
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_DATA_MAX_CONCURRENT_WRITES=64
      - INFLUXDB_DATA_MAX_BODY_SIZE=100MB
      - INFLUXDB_HTTP_MAX_CONNECTIONS=1024
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    depends_on:
      - influxdb
    image: grafana/grafana:latest
    networks:
      - my_net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

